name: Deployment dev

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      #- name: Test application
      #  run: |
      #    env: 
      #      API_URL: ${{ secrets.API_URL }}

      - name: Build application
        run: npm run build
        env: 
            API_URL: ${{ secrets.API_URL }}

      - name: Restart server application
        run: pm2 restart nest-js
